export const CERTIFICATE_SCREENSHOT_PRESET_SETTINGS = {
    orgName: 'فرع وزارة الصحة بمنطقة الحدود الشمالية',
    orgSubName: '',
    orgLogo: null,
    directorName: 'منصور بن سالم الرشيدي',
    directorTitle: 'مدير عام فرع وزارة الصحة بمنطقة الحدود الشمالية',
    directorSignature: null,
    visaLabel: 'التأشيرة',
    visaSignature: null,
    visaName: '',
    stamp: null,
    stampSize: 120,
    stampOpacity: 0.85,
    stampRotation: -8,
    primaryColor: '#0d7f55',
    goldColor: '#b29a57',
    certTitle: 'شهادة شكر وتقدير',
    certSubTitle: '',
    reasonPrefix: 'للزميل/ـة :',
    reasonText: 'سبب التكريم',
}

export function createScreenshotPresetLayers() {
    return [
        {
            id: 'name',
            type: 'text',
            label: 'اسم المستفيد',
            dataKey: 'name',
            x: 50,
            y: 42,
            width: 340,
            height: 60,
            visible: true,
            locked: false,
            zIndex: 12,
            style: {
                fontSize: 31,
                fontWeight: '900',
                color: '#1f4f86',
                fontFamily: 'Cairo',
                textAlign: 'center',
            },
        },
        {
            id: 'director-name',
            type: 'text',
            label: 'منصور بن سالم الرشيدي',
            dataKey: 'director-name',
            x: 45,
            y: 79.5,
            width: 260,
            height: 36,
            visible: true,
            locked: false,
            zIndex: 11,
            style: {
                fontSize: 22,
                fontWeight: '800',
                color: '#0d7f55',
                fontFamily: 'Cairo',
                textAlign: 'center',
            },
        },
        {
            id: 'intro-text',
            type: 'text',
            label: 'يتقدم فرع وزارة الصحة بمنطقة الحدود الشمالية بجزيل الشكر والتقدير',
            x: 50,
            y: 35.5,
            width: 520,
            height: 34,
            visible: true,
            locked: false,
            zIndex: 10,
            style: {
                fontSize: 16,
                fontWeight: '700',
                color: '#1f1f1f',
                fontFamily: 'Cairo',
                textAlign: 'center',
            },
        },
        {
            id: 'reason',
            type: 'text',
            label: 'سبب التكريم',
            dataKey: 'reason',
            x: 88,
            y: 47,
            width: 180,
            height: 30,
            visible: true,
            locked: false,
            zIndex: 9,
            style: {
                fontSize: 14,
                fontWeight: '600',
                color: '#1f1f1f',
                fontFamily: 'Cairo',
                textAlign: 'right',
            },
        },
        {
            id: 'recipient-prefix',
            type: 'text',
            label: 'للزميل/ـة :',
            x: 63,
            y: 42,
            width: 160,
            height: 34,
            visible: true,
            locked: false,
            zIndex: 8,
            style: {
                fontSize: 18,
                fontWeight: '800',
                color: '#0d7f55',
                fontFamily: 'Cairo',
                textAlign: 'right',
            },
        },
        {
            id: 'blessing-text',
            type: 'text',
            label: 'سائلين الله لكم التوفيق والسداد.',
            x: 49,
            y: 66.5,
            width: 340,
            height: 28,
            visible: true,
            locked: false,
            zIndex: 7,
            style: {
                fontSize: 16,
                fontWeight: '700',
                color: '#666666',
                fontFamily: 'Cairo',
                textAlign: 'center',
            },
        },
        {
            id: 'serial',
            type: 'text',
            label: 'رقم تسلسلي',
            dataKey: 'serial',
            x: 84,
            y: 73.5,
            width: 110,
            height: 22,
            visible: true,
            locked: false,
            zIndex: 6,
            style: {
                fontSize: 11,
                fontWeight: '500',
                color: '#6b7280',
                fontFamily: 'Cairo',
                textAlign: 'center',
            },
        },
        {
            id: 'director-sig',
            type: 'image',
            label: 'توقيع المدير',
            x: 39,
            y: 73,
            width: 140,
            height: 58,
            visible: true,
            locked: false,
            zIndex: 5,
            style: { opacity: 1 },
        },
        {
            id: 'director-title',
            type: 'text',
            label: 'مدير عام فرع وزارة الصحة بمنطقة الحدود الشمالية',
            x: 41,
            y: 72,
            width: 310,
            height: 30,
            visible: true,
            locked: false,
            zIndex: 5,
            style: {
                fontSize: 16,
                fontWeight: '800',
                color: '#0d7f55',
                fontFamily: 'Cairo',
                textAlign: 'center',
            },
        },
        {
            id: 'visa-sig',
            type: 'image',
            label: 'التأشيرة',
            x: 85,
            y: 71.5,
            width: 120,
            height: 62,
            visible: true,
            locked: false,
            zIndex: 5,
            style: { opacity: 1 },
        },
        {
            id: 'stamp',
            type: 'image',
            label: 'الختم',
            x: 60,
            y: 72.5,
            width: 126,
            height: 122,
            visible: true,
            locked: false,
            zIndex: 4,
            style: { opacity: 0.8, rotation: -8 },
        },
    ]
}
